apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-jes-sample"
spec:
  stages:
    - name: "production"
      sequences:
        - name: "k6-pass-seq"
          tasks:
            - name: "remote-passing-task"
        - name: "k6-fail-seq"
          tasks:
            - name: "remote-failing-task"